export interface DemoKnowledgeDocument {
  documentId: string;
  title: string;
  version: string;
  effectiveAt: string;
  expiresAt: string | null;
  status: "active" | "expired" | "draft";
  keywords: string[];
  excerpt: string;
}

export const demoKnowledgeDocuments: DemoKnowledgeDocument[] = [
  { documentId: "NET-001", title: "Interrupciones periódicas y luz roja", version: "2.1", effectiveAt: "2026-01-01", expiresAt: "2027-01-01", status: "active", keywords: ["internet", "desconecta", "módem", "modem", "luz", "roja", "e105"], excerpt: "Confirme si la luz roja permanece encendida o parpadea y registre el código mostrado por el módem." },
  { documentId: "NET-002", title: "Reinicio seguro del módem", version: "3.0", effectiveAt: "2026-02-01", expiresAt: null, status: "active", keywords: ["reiniciar", "reinicio", "módem", "modem", "energía"], excerpt: "Desconecte la energía durante 30 segundos, vuelva a conectar y espere hasta cinco minutos antes de evaluar las luces." },
  { documentId: "NET-003", title: "Cable de fibra desconectado", version: "1.4", effectiveAt: "2026-03-15", expiresAt: null, status: "active", keywords: ["fibra", "cable", "los", "rojo", "conector"], excerpt: "No doble ni retire el cable de fibra; verifique visualmente el conector y escale si la luz LOS está roja." },
  { documentId: "NET-004", title: "Cobertura Wi-Fi en la vivienda", version: "2.2", effectiveAt: "2026-01-20", expiresAt: null, status: "active", keywords: ["wifi", "wi-fi", "señal", "habitación", "alcance", "lento"], excerpt: "Compare la señal junto al módem y en la habitación afectada antes de recomendar un repetidor." },
  { documentId: "NET-005", title: "Credenciales de la red Wi-Fi", version: "1.1", effectiveAt: "2026-04-01", expiresAt: null, status: "active", keywords: ["contraseña", "password", "clave", "wifi", "nombre"], excerpt: "Valide la identidad del cliente antes de guiar un cambio de nombre o contraseña de la red." },
  { documentId: "NET-006", title: "Velocidad menor al plan", version: "4.0", effectiveAt: "2026-05-01", expiresAt: null, status: "active", keywords: ["velocidad", "lento", "plan", "mbps", "speedtest"], excerpt: "Solicite una prueba por cable Ethernet con un solo equipo conectado y registre descarga, subida y latencia." },
  { documentId: "NET-007", title: "Mantenimiento programado", version: "2026.09", effectiveAt: "2026-09-01", expiresAt: "2026-09-30", status: "active", keywords: ["mantenimiento", "zona", "interrupción", "programado"], excerpt: "Consulte la zona del cliente y la ventana vigente antes de atribuir la interrupción a mantenimiento." },
  { documentId: "NET-008", title: "Visita técnica domiciliaria", version: "2.0", effectiveAt: "2026-02-10", expiresAt: null, status: "active", keywords: ["técnico", "visita", "cita", "domicilio", "escalar"], excerpt: "Ofrezca una visita cuando las verificaciones remotas terminen y confirme fecha, franja horaria y teléfono de contacto." },
  { documentId: "NET-009", title: "Sin servicio después de una tormenta", version: "1.5", effectiveAt: "2026-06-01", expiresAt: null, status: "active", keywords: ["tormenta", "rayo", "lluvia", "sin", "servicio"], excerpt: "Revise primero incidentes de zona y no pida manipular cableado exterior después de una tormenta." },
  { documentId: "NET-010", title: "Dispositivo único sin conexión", version: "1.8", effectiveAt: "2026-01-05", expiresAt: null, status: "active", keywords: ["dispositivo", "teléfono", "laptop", "único", "conecta"], excerpt: "Compruebe si otros equipos navegan; si solo falla uno, olvide la red y vuelva a conectarlo." },
  { documentId: "NET-011", title: "Todos los dispositivos sin conexión", version: "1.7", effectiveAt: "2026-01-05", expiresAt: null, status: "active", keywords: ["todos", "ningún", "dispositivos", "teléfono", "computadora", "casa", "sin", "internet", "conexión"], excerpt: "Cuando ningún teléfono ni computadora de la casa tiene internet, verifique energía, luces WAN y existencia de una incidencia de zona antes de reiniciar el equipo." },
  { documentId: "NET-012", title: "Latencia alta en videojuegos", version: "1.3", effectiveAt: "2026-03-01", expiresAt: null, status: "active", keywords: ["latencia", "ping", "juego", "gaming", "lag"], excerpt: "Mida latencia por cable, descarte descargas simultáneas y registre el servidor utilizado por el juego." },
  { documentId: "NET-013", title: "Cambio de plan de internet", version: "2.5", effectiveAt: "2026-07-01", expiresAt: null, status: "active", keywords: ["cambiar", "subir", "plan", "precio", "cotización", "mayor", "velocidad", "contrato"], excerpt: "Para subir a un plan de mayor velocidad, explique precio, cotización y fecha efectiva; cualquier cambio requiere validación de identidad y confirmación contractual." },
  { documentId: "NET-014", title: "Factura con cargo de equipo", version: "1.2", effectiveAt: "2026-04-15", expiresAt: null, status: "active", keywords: ["factura", "cargo", "equipo", "módem", "precio"], excerpt: "Revise el inventario asociado y escale a facturación si el equipo fue devuelto con comprobante." },
  { documentId: "NET-015", title: "Código E105", version: "1.0", effectiveAt: "2026-08-01", expiresAt: null, status: "active", keywords: ["e105", "código", "error", "módem", "autenticación"], excerpt: "E105 indica un fallo de autenticación; confirme la luz WAN y escale con el código exacto si persiste tras el reinicio." },
  { documentId: "NET-016", title: "Procedimiento antiguo para luz roja", version: "0.8", effectiveAt: "2024-01-01", expiresAt: "2025-01-01", status: "expired", keywords: ["luz", "roja", "módem", "reinicio"], excerpt: "Restablezca el módem a valores de fábrica sin validaciones adicionales." },
  { documentId: "NET-017", title: "Borrador de diagnóstico automático", version: "0.1", effectiveAt: "2026-09-01", expiresAt: null, status: "draft", keywords: ["diagnóstico", "automático", "prueba"], excerpt: "Ejecute acciones remotas todavía no aprobadas por operaciones." },
  { documentId: "NET-018", title: "Escalación por riesgo eléctrico", version: "1.0", effectiveAt: "2026-05-20", expiresAt: null, status: "active", keywords: ["olor", "quemado", "caliente", "humo", "eléctrico"], excerpt: "Indique desconectar el equipo si es seguro hacerlo y escale de inmediato; no solicite nuevas pruebas eléctricas." },
  { documentId: "NET-019", title: "Daño físico del equipo", version: "1.1", effectiveAt: "2026-06-15", expiresAt: null, status: "active", keywords: ["roto", "daño", "golpe", "agua", "equipo"], excerpt: "Documente el daño visible y programe evaluación; no pida abrir ni reparar el módem." },
  { documentId: "NET-020", title: "Escalación sin procedimiento", version: "1.0", effectiveAt: "2026-01-01", expiresAt: null, status: "active", keywords: ["escalar", "problema", "desconocido", "no existe", "procedimiento", "aplicable"], excerpt: "Cuando un problema es desconocido y no existe un procedimiento aplicable, documente la categoría y escale sin inventar una solución." }
];
